apiVersion: v2
name: soli-portal
description: SOLI Enterprise Portal Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - soli
  - portal
  - nextjs
maintainers:
  - name: SOLI Team
    email: team@soli.com
